<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Task16.Dop">
      <HintPath>..\..\Task16.Dop\Task16.Dop\bin\Debug\Task16.Dop.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
