<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Task18">
      <HintPath>..\..\Task18\Task18\bin\Debug\net8.0\Task18.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
